// ABOUTME: Challenge database for all skills in the turtle curriculum
// ABOUTME: Contains typed commands, multiple choice, fix-error, and predict-output challenges

package tui

// getAllChallenges returns the complete challenge database organized by skill ID.
//
//nolint:funlen // Data definition function
func getAllChallenges() map[string][]Challenge {
	return map[string][]Challenge{
		// ====================
		// NAVIGATION
		// ====================
		"pwd": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "pwd",
				Prompt:      "Print the current working directory",
				Expected:    "pwd",
				Hint:        "Three letters: print working directory",
				Explanation: "pwd shows where you are in the filesystem",
			},
			{
				Type:        ChallengeTranslate,
				SkillID:     "pwd",
				Prompt:      "\"Where am I?\" translates to:",
				Expected:    "pwd",
				Hint:        "The command shows your current location",
				Explanation: "pwd = print working directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "pwd",
				Prompt:  "What does 'pwd' stand for?",
				Options: []string{
					"Print Working Directory",
					"Path to Working Directory",
					"Present Working Dir",
					"Print Where Directory",
				},
				Expected:    "0",
				Hint:        "It prints where you currently are",
				Explanation: "pwd = Print Working Directory",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "pwd",
				Prompt:        "If you're in /home/user/projects, what does pwd output?",
				BrokenCommand: "pwd",
				Options: []string{
					"/home/user/projects",
					"projects",
					"/home/user",
					"user/projects",
				},
				Expected:    "0",
				Hint:        "pwd shows the FULL path",
				Explanation: "pwd always shows the complete absolute path",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "pwd",
				Prompt:  "pwd shows which type of path?",
				Options: []string{
					"Absolute path",
					"Relative path",
					"Home path",
					"Short path",
				},
				Expected:    "0",
				Hint:        "It starts from the root /",
				Explanation: "pwd always shows the absolute (full) path from root",
			},
		},

		"ls": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List files in the current directory",
				Expected:    "ls",
				Hint:        "Two letters, short for 'list'",
				Explanation: "ls lists directory contents",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List ALL files (including hidden)",
				Expected:    "ls -a",
				Hint:        "Add the -a flag for 'all'",
				Explanation: "ls -a shows hidden files (starting with .)",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List files with details (long format)",
				Expected:    "ls -l",
				Hint:        "Add the -l flag for 'long'",
				Explanation: "ls -l shows permissions, size, dates",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List files with human-readable sizes",
				Expected:    "ls -lh",
				Hint:        "-h makes sizes readable (KB, MB, GB)",
				Explanation: "ls -lh shows sizes like 4.2K instead of 4200",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List files sorted by modification time (newest first)",
				Expected:    "ls -lt",
				Hint:        "-t sorts by time",
				Explanation: "ls -lt shows recently modified files first",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "ls",
				Prompt:      "List files in the /etc directory",
				Expected:    "ls /etc",
				Hint:        "ls followed by the path",
				Explanation: "ls <path> lists contents of that directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "ls",
				Prompt:  "Which flag shows hidden files?",
				Options: []string{
					"-a",
					"-h",
					"-l",
					"-s",
				},
				Expected:    "0",
				Hint:        "'a' for 'all'",
				Explanation: "-a shows ALL files including hidden ones (starting with .)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "ls",
				Prompt:  "What does the -l flag do?",
				Options: []string{
					"Long format with details",
					"List hidden files",
					"List recursively",
					"List by size",
				},
				Expected:    "0",
				Hint:        "l for 'long'",
				Explanation: "-l shows detailed info: permissions, owner, size, date",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "ls",
				Prompt:        "Fix this command to list hidden files:",
				BrokenCommand: "ls -h",
				Expected:      "ls -a",
				Hint:          "-h is for human-readable sizes, not hidden files",
				Explanation:   "-a shows hidden files, -h makes sizes human-readable",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "ls",
				Prompt:        "Fix this command to show long format:",
				BrokenCommand: "ls -i",
				Expected:      "ls -l",
				Hint:          "-i shows inode numbers, not details",
				Explanation:   "-l is for long format listing",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "ls",
				Prompt:        "A directory has files: app.js, .gitignore, README.md. What does 'ls' show?",
				BrokenCommand: "ls",
				Options: []string{
					"app.js README.md",
					"app.js .gitignore README.md",
					".gitignore only",
					"Nothing",
				},
				Expected:    "0",
				Hint:        "ls without -a hides dotfiles",
				Explanation: "Without -a, ls hides files starting with .",
			},
		},

		"cd": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Change to your home directory",
				Expected:    "cd",
				Hint:        "Just the command, no arguments",
				Explanation: "cd alone takes you home",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go to the /tmp directory",
				Expected:    "cd /tmp",
				Hint:        "cd followed by the path",
				Explanation: "cd <path> changes to that directory",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go up one directory level",
				Expected:    "cd ..",
				Hint:        "Two dots represent parent directory",
				Explanation: ".. always means 'parent directory'",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go to the previous directory you were in",
				Expected:    "cd -",
				Hint:        "Dash means 'previous'",
				Explanation: "cd - toggles between current and previous directory",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go to your home directory using ~",
				Expected:    "cd ~",
				Hint:        "Tilde is shorthand for home",
				Explanation: "~ expands to your home directory path",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go to user 'bob's home directory",
				Expected:    "cd ~bob",
				Hint:        "~username goes to that user's home",
				Explanation: "~bob expands to /home/bob (or similar)",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd",
				Prompt:      "Go up two directory levels",
				Expected:    "cd ../..",
				Hint:        "Chain the double dots with /",
				Explanation: "../.. means parent's parent directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cd",
				Prompt:  "What does '..' represent?",
				Options: []string{
					"Parent directory",
					"Current directory",
					"Home directory",
					"Root directory",
				},
				Expected:    "0",
				Hint:        "Two dots go UP one level",
				Explanation: ".. = parent directory, . = current directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cd",
				Prompt:  "What does '.' represent?",
				Options: []string{
					"Current directory",
					"Parent directory",
					"Home directory",
					"Hidden file prefix",
				},
				Expected:    "0",
				Hint:        "Single dot = where you are now",
				Explanation: ". represents the current directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cd",
				Prompt:  "What does 'cd -' do?",
				Options: []string{
					"Go to previous directory",
					"Go to parent directory",
					"Go to home directory",
					"Show current directory",
				},
				Expected:    "0",
				Hint:        "It's like an undo for cd",
				Explanation: "cd - takes you back to where you just were",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "cd",
				Prompt:        "Fix this command to go up one level:",
				BrokenCommand: "cd .",
				Expected:      "cd ..",
				Hint:          "One dot is current, two dots is parent",
				Explanation:   ". = current dir (no change), .. = parent dir (go up)",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "cd",
				Prompt:        "You're in /home/user/docs. After 'cd ..', where are you?",
				BrokenCommand: "cd ..",
				Options: []string{
					"/home/user",
					"/home/user/docs",
					"/home",
					"/",
				},
				Expected:    "0",
				Hint:        "Go UP one directory",
				Explanation: "cd .. moves you to the parent directory",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "cd",
				Prompt:        "You're in /var/log. After 'cd', where are you?",
				BrokenCommand: "cd",
				Options: []string{
					"Your home directory",
					"/var/log",
					"/var",
					"/",
				},
				Expected:    "0",
				Hint:        "cd with no arguments...",
				Explanation: "cd alone always takes you to your home directory",
			},
		},

		"cd-relative": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd-relative",
				Prompt:      "You're in /home/user. Go to /home/user/docs",
				Expected:    "cd docs",
				Hint:        "No leading slash = relative path",
				Explanation: "Without /, the path is relative to current directory",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cd-relative",
				Prompt:      "You're in /home/user/docs. Go to /home/user/music",
				Expected:    "cd ../music",
				Hint:        "Go up, then into sibling directory",
				Explanation: "Use .. to go up, then name the sibling directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cd-relative",
				Prompt:  "Which is a relative path?",
				Options: []string{
					"docs/project",
					"/home/user/docs",
					"/tmp",
					"/",
				},
				Expected:    "0",
				Hint:        "No leading slash",
				Explanation: "Relative paths don't start with /",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cd-relative",
				Prompt:  "Which is an absolute path?",
				Options: []string{
					"/home/user/docs",
					"docs/project",
					"../music",
					"./script.sh",
				},
				Expected:    "0",
				Hint:        "Starts from root",
				Explanation: "Absolute paths start with / (the root)",
			},
		},

		"tab-completion": {
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tab-completion",
				Prompt:  "What key triggers command/path completion?",
				Options: []string{
					"Tab",
					"Enter",
					"Space",
					"Escape",
				},
				Expected:    "0",
				Hint:        "It's called TAB completion",
				Explanation: "Press Tab to auto-complete commands and paths",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tab-completion",
				Prompt:  "What happens if you press Tab twice quickly?",
				Options: []string{
					"Shows all possible completions",
					"Cancels the command",
					"Runs the command",
					"Deletes the line",
				},
				Expected:    "0",
				Hint:        "Double-tab shows options",
				Explanation: "Double-tab lists all possible completions when ambiguous",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tab-completion",
				Prompt:  "You type 'cd /ho' and press Tab. What happens?",
				Options: []string{
					"Completes to 'cd /home/'",
					"Shows an error",
					"Nothing",
					"Runs 'cd /ho'",
				},
				Expected:    "0",
				Hint:        "Tab completes partial paths",
				Explanation: "Tab expands partial paths to their full form",
			},
		},

		// ====================
		// FILE OPERATIONS
		// ====================
		"mkdir": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mkdir",
				Prompt:      "Create a directory called 'projects'",
				Expected:    "mkdir projects",
				Hint:        "make directory",
				Explanation: "mkdir creates a new directory",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mkdir",
				Prompt:      "Create nested directories: projects/web/src",
				Expected:    "mkdir -p projects/web/src",
				Hint:        "-p creates parent directories too",
				Explanation: "mkdir -p creates all necessary parent directories",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mkdir",
				Prompt:      "Create multiple directories: docs, tests, src",
				Expected:    "mkdir docs tests src",
				Hint:        "List them all after mkdir",
				Explanation: "mkdir can create multiple directories at once",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "mkdir",
				Prompt:  "What does mkdir stand for?",
				Options: []string{
					"Make directory",
					"Move directory",
					"Modify directory",
					"Mark directory",
				},
				Expected:    "0",
				Hint:        "It MAKES something",
				Explanation: "mkdir = make directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "mkdir",
				Prompt:  "What does the -p flag do?",
				Options: []string{
					"Creates parent directories as needed",
					"Sets permissions",
					"Creates private directory",
					"Prompts before creating",
				},
				Expected:    "0",
				Hint:        "p for parents",
				Explanation: "-p creates the full path including any missing parent dirs",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "mkdir",
				Prompt:        "Fix this command to create nested directories a/b/c:",
				BrokenCommand: "mkdir a/b/c",
				Expected:      "mkdir -p a/b/c",
				Hint:          "Without -p, parent dirs must exist",
				Explanation:   "mkdir -p creates all necessary parent directories",
			},
		},

		"touch": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "touch",
				Prompt:      "Create an empty file called 'notes.txt'",
				Expected:    "touch notes.txt",
				Hint:        "The command 'touches' files into existence",
				Explanation: "touch creates empty files",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "touch",
				Prompt:      "Create multiple files: a.txt, b.txt, c.txt",
				Expected:    "touch a.txt b.txt c.txt",
				Hint:        "List them all after touch",
				Explanation: "touch can create multiple files at once",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "touch",
				Prompt:  "What happens if you touch a file that already exists?",
				Options: []string{
					"Updates the timestamp",
					"Deletes the file",
					"Shows an error",
					"Creates a backup",
				},
				Expected:    "0",
				Hint:        "It 'touches' the file gently",
				Explanation: "touch updates the modification time of existing files",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "touch",
				Prompt:  "Why is it called 'touch'?",
				Options: []string{
					"It updates file timestamps (like touching it)",
					"You touch the keyboard to run it",
					"It touches the disk",
					"No particular reason",
				},
				Expected:    "0",
				Hint:        "Think about what timestamps represent",
				Explanation: "touch 'touches' a file to update its access/modify times",
			},
		},

		"rm": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "rm",
				Prompt:      "Remove a file called 'temp.txt'",
				Expected:    "rm temp.txt",
				Hint:        "rm = remove",
				Explanation: "rm deletes files (careful - no undo!)",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "rm",
				Prompt:      "Remove a directory and all its contents",
				Expected:    "rm -r dirname",
				Hint:        "-r for recursive",
				Explanation: "rm -r removes directories and their contents recursively",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "rm",
				Prompt:      "Remove a file but ask for confirmation first",
				Expected:    "rm -i file.txt",
				Hint:        "-i for interactive",
				Explanation: "rm -i prompts before each removal",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "rm",
				Prompt:      "Force remove a file without confirmation",
				Expected:    "rm -f file.txt",
				Hint:        "-f for force",
				Explanation: "rm -f forces removal without prompts",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "rm",
				Prompt:  "What does 'rm -rf' do?",
				Options: []string{
					"Recursively force delete (dangerous!)",
					"Remove files safely",
					"Remove to recycle bin",
					"Remove with backup",
				},
				Expected:    "0",
				Hint:        "-r recursive, -f force",
				Explanation: "rm -rf is powerful and dangerous - no confirmation, no undo",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "rm",
				Prompt:  "Can you recover files deleted with rm?",
				Options: []string{
					"No (without special tools)",
					"Yes, from trash",
					"Yes, with Ctrl+Z",
					"Yes, always",
				},
				Expected:    "0",
				Hint:        "There's no trash can in the terminal",
				Explanation: "rm permanently deletes files - there's no built-in undo",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "rm",
				Prompt:        "Fix this command to remove a directory with contents:",
				BrokenCommand: "rm mydir",
				Expected:      "rm -r mydir",
				Hint:          "Directories need the recursive flag",
				Explanation:   "rm alone can't remove directories - use -r for recursive",
			},
		},

		"cp": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cp",
				Prompt:      "Copy file.txt to backup.txt",
				Expected:    "cp file.txt backup.txt",
				Hint:        "cp source destination",
				Explanation: "cp copies files: cp <source> <destination>",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cp",
				Prompt:      "Copy a directory and all its contents",
				Expected:    "cp -r srcdir destdir",
				Hint:        "-r for recursive",
				Explanation: "cp -r copies directories recursively",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cp",
				Prompt:      "Copy file.txt to the /tmp directory",
				Expected:    "cp file.txt /tmp",
				Hint:        "Destination can be a directory",
				Explanation: "When dest is a directory, file is copied into it",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cp",
				Prompt:      "Copy multiple files to a directory",
				Expected:    "cp a.txt b.txt c.txt destdir/",
				Hint:        "List files, then destination directory",
				Explanation: "cp can copy multiple files to one directory",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cp",
				Prompt:  "What happens if destination file exists?",
				Options: []string{
					"It gets overwritten",
					"Error is shown",
					"Backup is created",
					"User is prompted",
				},
				Expected:    "0",
				Hint:        "cp doesn't ask by default",
				Explanation: "cp overwrites without asking (use -i for prompts)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cp",
				Prompt:  "What does 'cp -r' do?",
				Options: []string{
					"Copy directories recursively",
					"Copy read-only files",
					"Copy with rename",
					"Copy to remote",
				},
				Expected:    "0",
				Hint:        "r for recursive",
				Explanation: "cp -r copies directories and all their contents",
			},
		},

		"mv": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mv",
				Prompt:      "Rename file.txt to document.txt",
				Expected:    "mv file.txt document.txt",
				Hint:        "mv is also used for renaming",
				Explanation: "mv moves OR renames files",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mv",
				Prompt:      "Move file.txt to the /tmp directory",
				Expected:    "mv file.txt /tmp",
				Hint:        "mv source destination",
				Explanation: "mv moves files to a new location",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "mv",
				Prompt:      "Move and rename: file.txt to /tmp/newname.txt",
				Expected:    "mv file.txt /tmp/newname.txt",
				Hint:        "Move and rename in one command",
				Explanation: "mv can move and rename simultaneously",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "mv",
				Prompt:  "How do you rename a file in Linux?",
				Options: []string{
					"Use mv command",
					"Use rename command",
					"Use rn command",
					"Use cp then rm",
				},
				Expected:    "0",
				Hint:        "mv has two uses",
				Explanation: "mv is used for both moving AND renaming",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "mv",
				Prompt:  "Does mv need -r to move directories?",
				Options: []string{
					"No, mv handles directories automatically",
					"Yes, always",
					"Only for non-empty directories",
					"Only on Linux",
				},
				Expected:    "0",
				Hint:        "mv is smarter than cp",
				Explanation: "Unlike cp, mv doesn't need -r for directories",
			},
		},

		"cat": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cat",
				Prompt:      "Display the contents of file.txt",
				Expected:    "cat file.txt",
				Hint:        "cat = concatenate (but also displays)",
				Explanation: "cat outputs file contents to the terminal",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cat",
				Prompt:      "Display contents with line numbers",
				Expected:    "cat -n file.txt",
				Hint:        "-n for numbers",
				Explanation: "cat -n shows line numbers",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "cat",
				Prompt:      "Combine two files into one output",
				Expected:    "cat file1.txt file2.txt",
				Hint:        "cat = concatenate",
				Explanation: "cat can concatenate multiple files",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cat",
				Prompt:  "What does 'cat' stand for?",
				Options: []string{
					"Concatenate",
					"Category",
					"Catalog",
					"It's just cat",
				},
				Expected:    "0",
				Hint:        "It joins things together",
				Explanation: "cat = concatenate, though often used just to display files",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "cat",
				Prompt:  "Best command to view a large file?",
				Options: []string{
					"less (cat floods the screen)",
					"cat",
					"echo",
					"print",
				},
				Expected:    "0",
				Hint:        "cat dumps everything at once",
				Explanation: "For large files, use less or more for pagination",
			},
		},

		"echo": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "echo",
				Prompt:      "Print 'Hello World' to the terminal",
				Expected:    "echo Hello World",
				Hint:        "echo repeats what you tell it",
				Explanation: "echo prints text to the terminal",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "echo",
				Prompt:      "Print text without a newline at the end",
				Expected:    "echo -n Hello",
				Hint:        "-n for no newline",
				Explanation: "echo -n doesn't add a newline at the end",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "echo",
				Prompt:      "Print the value of the HOME environment variable",
				Expected:    "echo $HOME",
				Hint:        "Use $ to access variables",
				Explanation: "$HOME contains your home directory path",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "echo",
				Prompt:      "Print the current PATH variable",
				Expected:    "echo $PATH",
				Hint:        "PATH tells the shell where to find commands",
				Explanation: "$PATH lists directories where commands are searched",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "echo",
				Prompt:  "What does 'echo $USER' display?",
				Options: []string{
					"Your username",
					"The word $USER literally",
					"All users on the system",
					"Nothing",
				},
				Expected:    "0",
				Hint:        "$ expands variables",
				Explanation: "$USER is an environment variable containing your username",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "echo",
				Prompt:  "How do you print a literal $ sign?",
				Options: []string{
					"Use single quotes: echo '$'",
					"echo $",
					"echo dollar",
					"You can't",
				},
				Expected:    "0",
				Hint:        "Single quotes prevent variable expansion",
				Explanation: "Single quotes treat everything literally, double quotes allow expansion",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "echo",
				Prompt:        "What does this output?",
				BrokenCommand: "echo \"Hello $USER\"",
				Options: []string{
					"Hello followed by your username",
					"Hello $USER literally",
					"Just Hello",
					"Error",
				},
				Expected:    "0",
				Hint:        "Double quotes allow variable expansion",
				Explanation: "In double quotes, $USER expands to your username",
			},
		},

		"head": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "head",
				Prompt:      "View the first 10 lines of a file",
				Expected:    "head file.txt",
				Hint:        "head shows the top of a file",
				Explanation: "head displays the first 10 lines by default",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "head",
				Prompt:      "View only the first 5 lines",
				Expected:    "head -n 5 file.txt",
				Hint:        "-n specifies number of lines",
				Explanation: "head -n N shows the first N lines",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "head",
				Prompt:      "View the first 20 bytes of a file",
				Expected:    "head -c 20 file.txt",
				Hint:        "-c for characters/bytes",
				Explanation: "head -c N shows the first N bytes",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "head",
				Prompt:  "How many lines does 'head' show by default?",
				Options: []string{
					"10",
					"5",
					"20",
					"All of them",
				},
				Expected:    "0",
				Hint:        "It's a round number",
				Explanation: "head shows 10 lines by default",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "head",
				Prompt:  "When is 'head' most useful?",
				Options: []string{
					"Quickly checking the start of large files",
					"Editing files",
					"Deleting files",
					"Moving files",
				},
				Expected:    "0",
				Hint:        "Think about previewing",
				Explanation: "head lets you peek at file contents without loading everything",
			},
		},

		"tail": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tail",
				Prompt:      "View the last 10 lines of a file",
				Expected:    "tail file.txt",
				Hint:        "tail shows the end of a file",
				Explanation: "tail displays the last 10 lines by default",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tail",
				Prompt:      "View only the last 3 lines",
				Expected:    "tail -n 3 file.txt",
				Hint:        "-n specifies number of lines",
				Explanation: "tail -n N shows the last N lines",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tail",
				Prompt:      "Follow a log file in real-time",
				Expected:    "tail -f logfile.txt",
				Hint:        "-f for follow",
				Explanation: "tail -f watches the file and shows new lines as they're added",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tail",
				Prompt:  "What does 'tail -f' do?",
				Options: []string{
					"Follows the file, showing new content live",
					"Shows the first lines",
					"Formats the output",
					"Filters the content",
				},
				Expected:    "0",
				Hint:        "f for follow",
				Explanation: "tail -f is perfect for watching log files in real-time",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tail",
				Prompt:  "Best use for 'tail -f'?",
				Options: []string{
					"Monitoring log files in real-time",
					"Editing files",
					"Copying files",
					"Deleting content",
				},
				Expected:    "0",
				Hint:        "Think about logs and debugging",
				Explanation: "tail -f is essential for watching logs while debugging",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "tail",
				Prompt:        "Fix this to show the last 5 lines:",
				BrokenCommand: "tail -5 file.txt",
				Expected:      "tail -n 5 file.txt",
				Hint:          "The proper flag is -n",
				Explanation:   "Use tail -n N to specify number of lines",
			},
		},

		"less": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "less",
				Prompt:      "Open a file in a pager",
				Expected:    "less file.txt",
				Hint:        "less is more than more",
				Explanation: "less allows scrolling through files",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "less",
				Prompt:  "How do you exit less?",
				Options: []string{
					"Press q",
					"Press Escape",
					"Press Ctrl-C",
					"Press Enter",
				},
				Expected:    "0",
				Hint:        "q for quit",
				Explanation: "Press q to quit less",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "less",
				Prompt:  "How do you search in less?",
				Options: []string{
					"Press / then type search term",
					"Press Ctrl-F",
					"Press s",
					"Type 'search'",
				},
				Expected:    "0",
				Hint:        "Same as vim",
				Explanation: "Press / to start a search, n for next match, N for previous",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "less",
				Prompt:  "How do you go to the end of a file in less?",
				Options: []string{
					"Press G (shift+g)",
					"Press End",
					"Press e",
					"Press Ctrl-E",
				},
				Expected:    "0",
				Hint:        "Capital G",
				Explanation: "G goes to end, g goes to beginning in less",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "less",
				Prompt:  "Why is 'less' better than 'cat' for large files?",
				Options: []string{
					"less lets you scroll and search",
					"less is faster",
					"less uses less memory",
					"less formats the output",
				},
				Expected:    "0",
				Hint:        "Think about navigation",
				Explanation: "less lets you navigate through files instead of dumping everything",
			},
		},

		"grep": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Search for 'error' in a log file",
				Expected:    "grep error log.txt",
				Hint:        "grep pattern filename",
				Explanation: "grep finds lines matching a pattern",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Search for 'error' case-insensitively",
				Expected:    "grep -i error log.txt",
				Hint:        "-i for ignore case",
				Explanation: "grep -i matches regardless of case",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Show line numbers with matches",
				Expected:    "grep -n error log.txt",
				Hint:        "-n for numbers",
				Explanation: "grep -n shows which line each match is on",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Search recursively in all files",
				Expected:    "grep -r error .",
				Hint:        "-r for recursive, . for current directory",
				Explanation: "grep -r searches all files in a directory tree",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Count how many lines match",
				Expected:    "grep -c error log.txt",
				Hint:        "-c for count",
				Explanation: "grep -c outputs just the count of matching lines",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "grep",
				Prompt:      "Show lines that DON'T match",
				Expected:    "grep -v error log.txt",
				Hint:        "-v for invert",
				Explanation: "grep -v shows lines that don't contain the pattern",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "grep",
				Prompt:  "What does 'grep' stand for?",
				Options: []string{
					"Global Regular Expression Print",
					"Get Regular Expression Pattern",
					"General Regex Parser",
					"Nothing, it's just a name",
				},
				Expected:    "0",
				Hint:        "It's an old Unix name",
				Explanation: "grep = Global Regular Expression Print (from ed command g/re/p)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "grep",
				Prompt:  "Which flag makes grep case-insensitive?",
				Options: []string{
					"-i",
					"-c",
					"-n",
					"-r",
				},
				Expected:    "0",
				Hint:        "i for ignore",
				Explanation: "-i makes grep ignore case differences",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "grep",
				Prompt:        "Fix this to search case-insensitively:",
				BrokenCommand: "grep -c Error log.txt",
				Expected:      "grep -i Error log.txt",
				Hint:          "-c counts matches, not case-insensitive",
				Explanation:   "Use -i for case-insensitive, -c for counting",
			},
		},

		"find": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "find",
				Prompt:      "Find all .txt files in current directory",
				Expected:    "find . -name \"*.txt\"",
				Hint:        "find path -name pattern",
				Explanation: "find searches for files matching criteria",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "find",
				Prompt:      "Find all directories named 'src'",
				Expected:    "find . -type d -name src",
				Hint:        "-type d for directories",
				Explanation: "find -type d finds only directories",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "find",
				Prompt:      "Find files modified in the last day",
				Expected:    "find . -mtime -1",
				Hint:        "-mtime for modification time",
				Explanation: "find -mtime -1 finds files modified within 24 hours",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "find",
				Prompt:      "Find empty files",
				Expected:    "find . -empty",
				Hint:        "There's a flag for empty",
				Explanation: "find -empty finds files and directories with no content",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "find",
				Prompt:  "What does '-type f' mean in find?",
				Options: []string{
					"Find only regular files",
					"Find fast",
					"Find formatted",
					"Find first",
				},
				Expected:    "0",
				Hint:        "f for file",
				Explanation: "-type f finds only regular files, -type d finds directories",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "find",
				Prompt:  "Which searches file NAMES vs file CONTENTS?",
				Options: []string{
					"find searches names, grep searches contents",
					"grep searches names, find searches contents",
					"Both search contents",
					"Both search names",
				},
				Expected:    "0",
				Hint:        "find = file system, grep = text",
				Explanation: "find looks at file names/metadata, grep looks inside files",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "find",
				Prompt:        "Fix this to find .log files:",
				BrokenCommand: "find . -name .log",
				Expected:      "find . -name \"*.log\"",
				Hint:          "You need a wildcard pattern",
				Explanation:   "Use *.log to match all files ending in .log",
			},
		},

		"pipes": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "pipes",
				Prompt:      "List files and search for 'txt' in the output",
				Expected:    "ls | grep txt",
				Hint:        "Use | to connect commands",
				Explanation: "Pipe sends output of ls to grep's input",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "pipes",
				Prompt:      "Count how many files are in a directory",
				Expected:    "ls | wc -l",
				Hint:        "wc -l counts lines",
				Explanation: "Pipe ls output to wc -l to count entries",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "pipes",
				Prompt:      "Show only the first 5 files listed",
				Expected:    "ls | head -n 5",
				Hint:        "Pipe to head",
				Explanation: "Pipe ls to head to limit output",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "pipes",
				Prompt:      "Search log for errors and count them",
				Expected:    "grep error log.txt | wc -l",
				Hint:        "Chain grep then wc",
				Explanation: "You can chain multiple commands with pipes",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "pipes",
				Prompt:  "What does the pipe | do?",
				Options: []string{
					"Sends output of one command as input to another",
					"Runs commands in parallel",
					"Saves output to a file",
					"Combines two files",
				},
				Expected:    "0",
				Hint:        "Think of a physical pipe",
				Explanation: "Pipe connects stdout of one command to stdin of the next",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "pipes",
				Prompt:  "In 'cat file | grep error | wc -l', what does wc count?",
				Options: []string{
					"Lines containing 'error'",
					"All lines in file",
					"The word 'error'",
					"All words in file",
				},
				Expected:    "0",
				Hint:        "wc -l counts what comes IN",
				Explanation: "wc counts the lines that grep outputs (matching lines)",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "pipes",
				Prompt:        "File has 100 lines, 10 contain 'error'. What's the output?",
				BrokenCommand: "grep error log.txt | wc -l",
				Options: []string{
					"10",
					"100",
					"error",
					"log.txt",
				},
				Expected:    "0",
				Hint:        "grep finds 10, wc counts them",
				Explanation: "grep outputs 10 lines, wc -l counts those 10 lines",
			},
		},

		"redirect": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "redirect",
				Prompt:      "Save 'Hello' to a file called greeting.txt",
				Expected:    "echo Hello > greeting.txt",
				Hint:        "> redirects to file",
				Explanation: "> creates/overwrites a file with the output",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "redirect",
				Prompt:      "Append 'World' to greeting.txt",
				Expected:    "echo World >> greeting.txt",
				Hint:        ">> appends instead of overwriting",
				Explanation: ">> adds to the end of a file without erasing",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "redirect",
				Prompt:      "Save directory listing to files.txt",
				Expected:    "ls > files.txt",
				Hint:        "Redirect ls output",
				Explanation: "Any command's output can be redirected to a file",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "redirect",
				Prompt:      "Redirect errors to error.log",
				Expected:    "command 2> error.log",
				Hint:        "2> redirects stderr",
				Explanation: "2> redirects error output (stderr) to a file",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "redirect",
				Prompt:  "What's the difference between > and >>?",
				Options: []string{
					"> overwrites, >> appends",
					">> overwrites, > appends",
					"They're the same",
					"> is faster",
				},
				Expected:    "0",
				Hint:        "One is more aggressive",
				Explanation: "> replaces file contents, >> adds to the end",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "redirect",
				Prompt:  "What does 2> redirect?",
				Options: []string{
					"Standard error (stderr)",
					"Second output",
					"Standard output (stdout)",
					"Second file",
				},
				Expected:    "0",
				Hint:        "2 is the stderr file descriptor",
				Explanation: "2 refers to stderr, 1 is stdout, 0 is stdin",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "redirect",
				Prompt:        "Fix this to append instead of overwrite:",
				BrokenCommand: "echo log entry > app.log",
				Expected:      "echo log entry >> app.log",
				Hint:          "Double the redirect symbol",
				Explanation:   "Use >> to append, > will erase existing content",
			},
		},

		"history": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "history",
				Prompt:      "Show your command history",
				Expected:    "history",
				Hint:        "Just type the command",
				Explanation: "history shows recently executed commands",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "history",
				Prompt:      "Show the last 10 commands",
				Expected:    "history 10",
				Hint:        "Add a number",
				Explanation: "history N shows the last N commands",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "history",
				Prompt:  "How do you run the previous command again?",
				Options: []string{
					"Press up arrow or type !!",
					"Type 'again'",
					"Press Tab",
					"Type 'repeat'",
				},
				Expected:    "0",
				Hint:        "!! is called bang bang",
				Explanation: "!! repeats the last command, up arrow lets you edit it first",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "history",
				Prompt:  "What does Ctrl-R do?",
				Options: []string{
					"Reverse search through history",
					"Repeat last command",
					"Remove from history",
					"Reset terminal",
				},
				Expected:    "0",
				Hint:        "R for reverse",
				Explanation: "Ctrl-R lets you search backwards through command history",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "history",
				Prompt:  "How do you run command #42 from history?",
				Options: []string{
					"!42",
					"history 42",
					"run 42",
					"#42",
				},
				Expected:    "0",
				Hint:        "! runs from history",
				Explanation: "!N runs command number N from your history",
			},
		},

		"man": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "man",
				Prompt:      "Read the manual for the ls command",
				Expected:    "man ls",
				Hint:        "man commandname",
				Explanation: "man shows the manual page for any command",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "man",
				Prompt:  "What does 'man' stand for?",
				Options: []string{
					"Manual",
					"Manager",
					"Manipulate",
					"Main",
				},
				Expected:    "0",
				Hint:        "Documentation",
				Explanation: "man = manual, it shows documentation",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "man",
				Prompt:  "How do you exit a man page?",
				Options: []string{
					"Press q",
					"Press Escape",
					"Press Ctrl-C",
					"Type 'exit'",
				},
				Expected:    "0",
				Hint:        "Same as less",
				Explanation: "man pages use less as a pager, so q quits",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "man",
				Prompt:  "How do you search within a man page?",
				Options: []string{
					"Press / then type search term",
					"Press Ctrl-F",
					"Type 'find'",
					"Press s",
				},
				Expected:    "0",
				Hint:        "Same as less and vim",
				Explanation: "Press / to search, n for next match, N for previous",
			},
		},

		"which": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "which",
				Prompt:      "Find where the 'python' command is located",
				Expected:    "which python",
				Hint:        "which commandname",
				Explanation: "which shows the full path to a command",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "which",
				Prompt:  "What does 'which' show?",
				Options: []string{
					"The path to the command's executable",
					"Which user owns the command",
					"Which version is installed",
					"Which options are available",
				},
				Expected:    "0",
				Hint:        "Think about location",
				Explanation: "which shows where in your PATH the command is found",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "which",
				Prompt:  "Why is 'which' useful?",
				Options: []string{
					"To see which version of a command will run",
					"To run commands faster",
					"To install commands",
					"To delete commands",
				},
				Expected:    "0",
				Hint:        "Multiple versions might exist",
				Explanation: "which helps when you have multiple versions installed",
			},
			{
				Type:          ChallengePredictOutput,
				SkillID:       "which",
				Prompt:        "You have python in /usr/bin/. What does 'which python' show?",
				BrokenCommand: "which python",
				Options: []string{
					"/usr/bin/python",
					"python",
					"3.10",
					"installed",
				},
				Expected:    "0",
				Hint:        "Full path",
				Explanation: "which outputs the full path to the executable",
			},
		},

		"clear": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "clear",
				Prompt:      "Clear the terminal screen",
				Expected:    "clear",
				Hint:        "Just type the command",
				Explanation: "clear clears all text from the terminal",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "clear",
				Prompt:  "What keyboard shortcut also clears the screen?",
				Options: []string{
					"Ctrl-L",
					"Ctrl-C",
					"Ctrl-D",
					"Ctrl-R",
				},
				Expected:    "0",
				Hint:        "L for... clear?",
				Explanation: "Ctrl-L clears the screen without typing 'clear'",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "clear",
				Prompt:  "Does 'clear' delete your command history?",
				Options: []string{
					"No, just clears the display",
					"Yes, all history is gone",
					"Only the last 10 commands",
					"It depends on settings",
				},
				Expected:    "0",
				Hint:        "It's just visual",
				Explanation: "clear only affects the display, history is preserved",
			},
		},

		// ====================
		// TMUX BASICS
		// ====================
		"tmux-why": {
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-why",
				Prompt:  "What problem does tmux solve?",
				Options: []string{
					"Sessions persist after disconnect",
					"Makes terminal colorful",
					"Speeds up commands",
					"Provides a GUI",
				},
				Expected:    "0",
				Hint:        "What happens when you close your laptop?",
				Explanation: "tmux keeps sessions running even after you disconnect",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-why",
				Prompt:  "What does 'tmux' stand for?",
				Options: []string{
					"Terminal Multiplexer",
					"Terminal Max",
					"Time Multiplex",
					"Text Mux",
				},
				Expected:    "0",
				Hint:        "It multiplexes terminals",
				Explanation: "tmux = terminal multiplexer",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-why",
				Prompt:  "Which is NOT a tmux benefit?",
				Options: []string{
					"Runs commands faster",
					"Persistent sessions",
					"Split terminal into panes",
					"Multiple windows",
				},
				Expected:    "0",
				Hint:        "tmux is about organization, not speed",
				Explanation: "tmux doesn't make commands faster, but provides persistence and organization",
			},
		},

		"tmux-new": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-new",
				Prompt:      "Start a new tmux session",
				Expected:    "tmux",
				Hint:        "Just run tmux",
				Explanation: "Running 'tmux' alone starts a new session",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-new",
				Prompt:      "Start a new tmux session named 'work'",
				Expected:    "tmux new -s work",
				Hint:        "tmux new -s <name>",
				Explanation: "tmux new -s creates a named session",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-new",
				Prompt:      "Start a new session named 'dev' with window named 'code'",
				Expected:    "tmux new -s dev -n code",
				Hint:        "-n names the first window",
				Explanation: "-s names the session, -n names the first window",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-new",
				Prompt:  "What does the -s flag do in 'tmux new -s'?",
				Options: []string{
					"Names the session",
					"Starts silently",
					"Shows status",
					"Saves the session",
				},
				Expected:    "0",
				Hint:        "-s for session name",
				Explanation: "-s lets you give the session a name for easy identification",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "tmux-new",
				Prompt:        "Fix this command to create a session named 'dev':",
				BrokenCommand: "tmux new dev",
				Expected:      "tmux new -s dev",
				Hint:          "You need a flag to specify the name",
				Explanation:   "Use -s to name the session: tmux new -s <name>",
			},
		},

		"tmux-prefix": {
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-prefix",
				Prompt:  "What is the default tmux prefix key?",
				Options: []string{
					"Ctrl-b",
					"Ctrl-a",
					"Ctrl-t",
					"Ctrl-x",
				},
				Expected:    "0",
				Hint:        "b is the default",
				Explanation: "Ctrl-b is tmux's default prefix (many change it to Ctrl-a)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-prefix",
				Prompt:  "Why does tmux use a prefix key?",
				Options: []string{
					"To distinguish tmux commands from terminal input",
					"To make it harder to use",
					"Historical reasons only",
					"It doesn't need one",
				},
				Expected:    "0",
				Hint:        "How else would tmux know you're talking to it?",
				Explanation: "The prefix tells tmux the next key is a command, not terminal input",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-prefix",
				Prompt:  "How do you type a literal Ctrl-b in tmux?",
				Options: []string{
					"Press Ctrl-b twice",
					"You can't",
					"Press Ctrl-b then b",
					"Use escape first",
				},
				Expected:    "0",
				Hint:        "Double-tap the prefix",
				Explanation: "Ctrl-b Ctrl-b sends an actual Ctrl-b to the terminal",
			},
		},

		"tmux-detach": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-detach",
				Prompt:      "Detach from current tmux session (key combo)",
				Expected:    "Ctrl-b d",
				Hint:        "Prefix key + d",
				Explanation: "Ctrl-b is the prefix, then d for detach",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-detach",
				Prompt:  "What happens when you detach from tmux?",
				Options: []string{
					"Session keeps running in background",
					"Session is paused",
					"Session is terminated",
					"Session is saved to disk",
				},
				Expected:    "0",
				Hint:        "That's the whole point of tmux",
				Explanation: "Detaching leaves the session running - you can reattach later",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-detach",
				Prompt:  "Your SSH connection drops. What happens to your tmux session?",
				Options: []string{
					"It keeps running",
					"It terminates",
					"It pauses",
					"It crashes",
				},
				Expected:    "0",
				Hint:        "This is why tmux exists",
				Explanation: "tmux sessions survive disconnects - just reattach when you reconnect",
			},
		},

		"tmux-attach": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-attach",
				Prompt:      "Reattach to your most recent tmux session",
				Expected:    "tmux attach",
				Hint:        "Or 'tmux a' for short",
				Explanation: "tmux attach reconnects to the last session",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-attach",
				Prompt:      "Attach to a tmux session named 'work'",
				Expected:    "tmux attach -t work",
				Hint:        "tmux attach -t <name>",
				Explanation: "attach -t lets you reconnect to a named session",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-attach",
				Prompt:  "What does -t stand for in 'tmux attach -t'?",
				Options: []string{
					"Target session",
					"Terminal",
					"Time",
					"Tab",
				},
				Expected:    "0",
				Hint:        "You're targeting a specific session",
				Explanation: "-t specifies the target session to attach to",
			},
			{
				Type:          ChallengeFixError,
				SkillID:       "tmux-attach",
				Prompt:        "Fix this command to attach to session 'dev':",
				BrokenCommand: "tmux attach dev",
				Expected:      "tmux attach -t dev",
				Hint:          "Need a flag for the target",
				Explanation:   "Use -t to specify the target session",
			},
		},

		"tmux-list": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-list",
				Prompt:      "List all tmux sessions",
				Expected:    "tmux ls",
				Hint:        "ls = list sessions",
				Explanation: "tmux ls shows all running sessions",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-list",
				Prompt:      "Alternative way to list sessions",
				Expected:    "tmux list-sessions",
				Hint:        "The full command name",
				Explanation: "tmux list-sessions is the same as tmux ls",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-list",
				Prompt:  "What information does 'tmux ls' show?",
				Options: []string{
					"Session names, windows, and attached status",
					"Only session names",
					"Running commands",
					"Session history",
				},
				Expected:    "0",
				Hint:        "It's quite informative",
				Explanation: "tmux ls shows session name, window count, creation time, and if attached",
			},
		},

		// ====================
		// TMUX PANES
		// ====================
		"tmux-split-h": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-split-h",
				Prompt:      "Split the current pane horizontally (side by side)",
				Expected:    "Ctrl-b %",
				Hint:        "% looks like two columns",
				Explanation: "Ctrl-b % creates a vertical split (panes side by side)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-split-h",
				Prompt:  "What does Ctrl-b % create?",
				Options: []string{
					"Vertical split (panes side by side)",
					"Horizontal split (panes stacked)",
					"New window",
					"New session",
				},
				Expected:    "0",
				Hint:        "% has two halves",
				Explanation: "Ctrl-b % splits vertically, creating panes side by side",
			},
		},

		"tmux-split-v": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-split-v",
				Prompt:      "Split the current pane vertically (top/bottom)",
				Expected:    "Ctrl-b \"",
				Hint:        "\" looks like stacked lines",
				Explanation: "Ctrl-b \" creates a horizontal split (panes stacked)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-split-v",
				Prompt:  "What does Ctrl-b \" create?",
				Options: []string{
					"Horizontal split (panes stacked)",
					"Vertical split (panes side by side)",
					"New window",
					"New session",
				},
				Expected:    "0",
				Hint:        "\" has horizontal lines",
				Explanation: "Ctrl-b \" splits horizontally, stacking panes top/bottom",
			},
		},

		"tmux-pane-nav": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-nav",
				Prompt:      "Move to the next pane",
				Expected:    "Ctrl-b o",
				Hint:        "o for 'other'",
				Explanation: "Ctrl-b o cycles to the next pane",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-nav",
				Prompt:      "Move to the pane above",
				Expected:    "Ctrl-b Up",
				Hint:        "Use arrow keys",
				Explanation: "Ctrl-b followed by arrow keys moves to adjacent panes",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-nav",
				Prompt:      "Move to the pane on the left",
				Expected:    "Ctrl-b Left",
				Hint:        "Arrow keys navigate panes",
				Explanation: "Ctrl-b + arrow key moves to that direction's pane",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-pane-nav",
				Prompt:  "Which shows pane numbers for quick switching?",
				Options: []string{
					"Ctrl-b q",
					"Ctrl-b n",
					"Ctrl-b p",
					"Ctrl-b o",
				},
				Expected:    "0",
				Hint:        "q for query/quick",
				Explanation: "Ctrl-b q shows pane numbers, then press the number to switch",
			},
		},

		"tmux-pane-resize": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-resize",
				Prompt:      "Resize pane: make it taller",
				Expected:    "Ctrl-b Ctrl-Up",
				Hint:        "Hold Ctrl, press b, keep holding Ctrl, press Up",
				Explanation: "Ctrl-b Ctrl-Arrow resizes panes",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-resize",
				Prompt:      "Resize pane: make it wider",
				Expected:    "Ctrl-b Ctrl-Right",
				Hint:        "Ctrl stays held down",
				Explanation: "Ctrl-b Ctrl-Right expands pane to the right",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-pane-resize",
				Prompt:  "What's the difference between Ctrl-b Up and Ctrl-b Ctrl-Up?",
				Options: []string{
					"Up navigates, Ctrl-Up resizes",
					"Both navigate",
					"Both resize",
					"Up resizes, Ctrl-Up navigates",
				},
				Expected:    "0",
				Hint:        "Extra Ctrl changes the action",
				Explanation: "Without extra Ctrl = navigate, with extra Ctrl = resize",
			},
		},

		"tmux-pane-close": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-pane-close",
				Prompt:      "Close the current pane",
				Expected:    "Ctrl-b x",
				Hint:        "x marks it for exit",
				Explanation: "Ctrl-b x closes the current pane (with confirmation)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-pane-close",
				Prompt:  "What happens when you close the last pane?",
				Options: []string{
					"The window closes",
					"A new pane opens",
					"Nothing",
					"tmux exits",
				},
				Expected:    "0",
				Hint:        "Panes live inside windows",
				Explanation: "Closing the last pane closes the window (and maybe session)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-pane-close",
				Prompt:  "Another way to close a pane?",
				Options: []string{
					"Type 'exit' or Ctrl-d",
					"Press Escape",
					"Press q",
					"Close terminal app",
				},
				Expected:    "0",
				Hint:        "How do you normally exit a shell?",
				Explanation: "exit or Ctrl-d closes the shell, which closes the pane",
			},
		},

		// ====================
		// TMUX WINDOWS
		// ====================
		"tmux-window-new": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-new",
				Prompt:      "Create a new window",
				Expected:    "Ctrl-b c",
				Hint:        "c for create",
				Explanation: "Ctrl-b c creates a new window",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-window-new",
				Prompt:  "What's the difference between a pane and a window?",
				Options: []string{
					"Panes split the screen, windows are separate screens",
					"They're the same thing",
					"Windows split the screen, panes are separate",
					"Panes are in session, windows are separate",
				},
				Expected:    "0",
				Hint:        "Think of windows as tabs",
				Explanation: "Windows are like tabs, panes split a single window",
			},
		},

		"tmux-window-nav": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-nav",
				Prompt:      "Go to the next window",
				Expected:    "Ctrl-b n",
				Hint:        "n for next",
				Explanation: "Ctrl-b n moves to the next window",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-nav",
				Prompt:      "Go to the previous window",
				Expected:    "Ctrl-b p",
				Hint:        "p for previous",
				Explanation: "Ctrl-b p moves to the previous window",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-nav",
				Prompt:      "Go to window number 3",
				Expected:    "Ctrl-b 3",
				Hint:        "Direct number access",
				Explanation: "Ctrl-b followed by a number jumps to that window",
			},
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-nav",
				Prompt:      "Switch to the last used window",
				Expected:    "Ctrl-b l",
				Hint:        "l for last",
				Explanation: "Ctrl-b l toggles between current and last window",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-window-nav",
				Prompt:  "Window numbers start at:",
				Options: []string{
					"0",
					"1",
					"Depends on config",
					"Random",
				},
				Expected:    "0",
				Hint:        "Programmers count from...",
				Explanation: "tmux window numbers start at 0 by default",
			},
		},

		"tmux-window-rename": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-rename",
				Prompt:      "Rename the current window",
				Expected:    "Ctrl-b ,",
				Hint:        "Comma prompts for a name",
				Explanation: "Ctrl-b , lets you rename the current window",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-window-rename",
				Prompt:  "Why rename windows?",
				Options: []string{
					"Easier to identify what's in each window",
					"Required for tmux to work",
					"Makes windows faster",
					"Saves memory",
				},
				Expected:    "0",
				Hint:        "Organization matters",
				Explanation: "Named windows like 'code', 'logs', 'server' help navigation",
			},
		},

		"tmux-window-close": {
			{
				Type:        ChallengeTypeCommand,
				SkillID:     "tmux-window-close",
				Prompt:      "Close the current window",
				Expected:    "Ctrl-b &",
				Hint:        "& asks for confirmation",
				Explanation: "Ctrl-b & closes the current window (with confirmation)",
			},
			{
				Type:    ChallengeMultipleChoice,
				SkillID: "tmux-window-close",
				Prompt:  "What happens when you close the last window?",
				Options: []string{
					"The session ends",
					"A new window is created",
					"Nothing",
					"Error is shown",
				},
				Expected:    "0",
				Hint:        "Windows live in sessions",
				Explanation: "Closing the last window terminates the session",
			},
		},
	}
}
